[package]
name = "wasi-http-handler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
http = "0.2"
thiserror = "1"
wit-bindgen = { version = "0.5.0", default_features = false }

[package.metadata.component.target]
path = "wit"
world = "world"